---
deployment:
  tasks:
    - export DEPLOYPATH=/home/marmklin/public_html/test/
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp *.png $DEPLOYPATH
    - /bin/cp *.jpg $DEPLOYPATH
    - /bin/cp *.jpeg $DEPLOYPATH
